### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by syarihu**
Please release 🙇

### CODE REVIEW

**Comment by perettijuan** [comment]
+1 on this release request.

**Comment by syarihu** [comment]
@rharter
Please release this version :bow:

**Comment by syarihu** [comment]
@rharter Is there anything else I need to do to release?

**Comment by rharter** [comment]
Sorry for the silence. I'm not at a computer this weekend, but will release
this next week.

**Comment by syarihu** [comment]
No problem, thank you 🙇 
I am eagerly awaiting the release.

**Comment by rharter** [comment]
Sorry for the long wait.  This has been released!

**Comment by syarihu** [comment]
Thanks for release this!

**Pull request merged**
